Repository AY2223S1-CS2103T-W11-2/tp, pull requests merged in 2022-10, with the labels that each got.

#56 Add module class
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleDescription.java
  src/main/java/seedu/address/model/module/ModuleName.java
Labels: enhancement

#63 Update module class
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, priority.High

#73 Add AddModuleCommand and relevant tests
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: enhancement, priority.High

#77 Branch module list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/module/ModuleListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ModuleListCommandTest.java
Labels: enhancement, priority.High

#78 Add DeleteModuleCommand and relevant tests
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModuleCodes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: enhancement, priority.High

#82 Update user guide with madd and mdel
  docs/UserGuide.md
  docs/images/userguide/madd.png
  docs/images/userguide/mdel.png
Labels: documentation

#90 Add mview command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewModuleScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/commands/module/ModuleListCommand.java
  src/main/java/seedu/address/logic/commands/module/ModuleViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ModuleViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/StudentContainsModulePredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleInfoPanel.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleInfoPanel.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ModuleListCommandTest.java
Labels: enhancement, priority.High

#91 Add more tests to module package
  src/test/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
Labels: enhancement, priority.High

#95 Add teaching assistant field to student class
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/parser/AddStuCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/StudentContainsModulePredicateTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: priority.High, type.Chore

#108 Update GUI to show correct page for each command
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/module/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/module/DeleteModuleCommandTest.java
Labels: enhancement, priority.High

#113 Finish DeleteSchedule and fix schedule bugs
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#114 Add test cases for Module in logic package
  src/test/java/seedu/address/logic/commands/module/ModuleViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ModuleViewCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalModuleCodes.java
Labels: priority.High, type.Chore

#120 Enable assertions for tP
  build.gradle
Labels: priority.High

#117 Add EditModuleCommand and relevant tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/model/module/ModuleCodeContainsKeywordPredicate.java
  src/main/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/module/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/ModuleViewCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleCodeContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModuleCodes.java
Labels: enhancement, priority.High

#123 Add TA list to mview command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/module/ModuleViewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/TutorContainsModulePredicate.java
  src/main/java/seedu/address/model/person/UniqueTutorList.java
  src/main/java/seedu/address/model/person/exceptions/PersonTypeException.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/java/seedu/address/ui/TutorListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorListCard.fxml
  src/main/resources/view/TutorListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/TutorContainsModulePredicateTest.java
  src/test/java/seedu/address/model/person/UniqueTutorListTest.java
  src/test/java/seedu/address/testutil/TypicalTutors.java
Labels: enhancement, priority.High

#126 Branch new view time table
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewModuleScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/schedule/ScheduleContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
Labels: enhancement

#134 Add DG with mview implementation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewModuleActivityDiagram.puml
  docs/diagrams/ViewModuleSequenceDiagram.puml
  docs/images/ViewModuleActivityDiagram.png
  docs/images/ViewModuleSequenceDiagram.png
  docs/team/bryanngzh.md
  docs/team/drkkjh.md
  docs/team/leongdl135.md
  docs/team/lizekai-richard.md
  docs/team/myangat0343.md
Labels: documentation, priority.High

#146 Update UG and DG with ViewScheduleCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewScheduleSequenceDiagram.puml
  docs/images/ViewScheduleSequenceDiagram.png
  docs/images/userguide/sclear.png
  docs/images/userguide/view.png
  src/main/java/seedu/address/logic/commands/schedule/ViewScheduleCommand.java
Labels: documentation

#149 Add grid view of schedule
  src/main/java/seedu/address/model/module/schedule/Schedule.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/schedule/ScheduleCard.java
  src/main/java/seedu/address/ui/schedule/ScheduleGridPanel.java
  src/main/java/seedu/address/ui/schedule/ScheduleListPanel.java
  src/main/java/seedu/address/ui/schedule/ScheduleSlotBlue.java
  src/main/java/seedu/address/ui/schedule/ScheduleSlotGreen.java
  src/main/java/seedu/address/ui/schedule/ScheduleSlotRed.java
  src/main/java/seedu/address/ui/schedule/SlotContainer.java
  src/main/java/seedu/address/ui/schedule/WeekdayCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/schedule/ScheduleGridPanel.fxml
  src/main/resources/view/schedule/ScheduleListCard.fxml
  src/main/resources/view/schedule/ScheduleListPanel.fxml
  src/main/resources/view/schedule/ScheduleSlotBlue.fxml
  src/main/resources/view/schedule/ScheduleSlotGreen.fxml
  src/main/resources/view/schedule/ScheduleSlotRed.fxml
  src/main/resources/view/schedule/WeekdayCard.fxml
Labels: enhancement, priority.High

#172 Add more personal tone to index.md
  docs/index.md
Labels: documentation

#173 Update User Guide and fix bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: documentation, priority.High

#181 Add `vtarget` command specific to enhance `mlist`
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/module/ViewTargetModuleCommand.java
  src/main/java/seedu/address/logic/parser/ProfNusParser.java
  src/main/java/seedu/address/logic/parser/ViewTargetModuleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
Labels: enhancement, priority.High

#184 Fix bug of not allowing module to be created without tag
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
Labels: bug, priority.High

#186 Add Light mode and Dark mode command
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DarkModeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/LightModeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/module/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ViewModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ViewTargetModuleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ProfNusParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/theme/Theme.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStuCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ListModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ViewModuleCommandTest.java
Labels: enhancement, priority.High

#187 Fix bug of mlist showing all modules in targetModuleList and scheduleList
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug, priority.High

#189 Update userguide for vtarget
  docs/UserGuide.md
Labels: documentation

#190 Change landing page to display timetable
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#191 Update Student Command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
  src/main/java/seedu/address/logic/parser/AddStuCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStuCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditStuCommandParserTest.java
Labels: bug, priority.High

#192 Add light and dark mode command to UG
  docs/UserGuide.md
Labels: documentation

#194 Edit userguide with new specifications
  docs/UserGuide.md
Labels: documentation

#227 Fix student tab bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#250 Fix delete module bug
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
Labels: bug

#251 Reformat User Guide
  docs/UserGuide.md
Labels: documentation, type.Chore

#254 Close the div
  docs/DeveloperGuide.md
Labels: bug, documentation

#253 Fix mview bug
  src/main/java/seedu/address/logic/commands/module/ViewModuleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStuCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/AddModuleCommandTest.java
Labels: bug

#256 Fix madd,mdel, medit bugs and added regex check for madd
  src/main/java/seedu/address/logic/commands/module/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
Labels: bug, priority.High

#257 Fix UG documentation for mview
  docs/UserGuide.md
Labels: bug, documentation
