Repository AY2223S1-CS2103T-W11-2/tp, pull requests merged in 2022-11, with the labels that each got.

#258 Fix documentation bug for `madd` in userguide
  docs/UserGuide.md
Labels: documentation, priority.High

#260 Fix bug where after running medit list of schedules get deleted
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
  src/main/java/seedu/address/model/module/Module.java
Labels: bug, priority.High

#265 Update PPP
  docs/AboutUs.md
  docs/team/bryanngzh.md
Labels: documentation, priority.High

#267 Update PPP
  docs/team/leongdl135.md
Labels: documentation, priority.High

#270 Update user guide with About section
  docs/UserGuide.md
Labels: documentation

#271 User Guide: Separate command summary
  docs/UserGuide.md
Labels: documentation

#272 Update PPP draft
  docs/team/drkkjh.md
Labels: documentation

#275 Update User Guide: Fix hyperlinks in command summary and bolding of words
  docs/UserGuide.md
Labels: documentation

#277 Fix hyperlinks for help and exit command
  docs/UserGuide.md
Labels: bug, documentation

#279 Add Introduction for DG
  docs/DeveloperGuide.md
Labels: documentation

#280 Update User Guide for Student
  docs/UserGuide.md
  docs/images/userguide/student/add_step1.png
  docs/images/userguide/student/add_step2.png
  docs/images/userguide/student/delstu_step1.png
  docs/images/userguide/student/delstu_step2.png
  docs/images/userguide/student/edit_step1.png
  docs/images/userguide/student/edit_step2.png
  docs/images/userguide/student/find_step1.png
  docs/images/userguide/student/find_step2.png
  docs/images/userguide/studentandta.png
Labels: documentation, priority.High

#282 Add Module Manager Command Parameters
  docs/UserGuide.md
Labels: documentation

#286 Fix Student Bug
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/JsonSerializableProfNusTest/typicalPersonsProfNus.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonSerializableProfNusTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: bug, priority.High

#288 Update DG Structure
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: documentation

#289 Update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditStuCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/EditStuCommandSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#290 Update developer guide with appendix
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: documentation

#291 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#287 Fix bugs for vtarget with correct resultDisplay
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DarkModeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/LightModeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/module/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ViewModuleCommand.java
  src/main/java/seedu/address/logic/commands/module/ViewTargetModuleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ViewScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/ViewTimeTableCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStuCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ListModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/module/ViewModuleCommandTest.java
Labels: bug, priority.High

#295 Update diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#296 Add test for ViewTargetModuleCommand
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/module/ViewTargetModuleCommandTest.java
Labels: priority.High

#300 Update UG with module details
  docs/UserGuide.md
  docs/images/userguide/madd_step1.png
  docs/images/userguide/madd_step2.png
  docs/images/userguide/mdel_step1.png
  docs/images/userguide/mdel_step2.png
  docs/images/userguide/medit_step1.png
  docs/images/userguide/medit_step2.png
  docs/images/userguide/mlist.png
  docs/images/userguide/mlist_step1.png
  docs/images/userguide/mlist_step2.png
  docs/images/userguide/mview_step1.png
  docs/images/userguide/vtarget_step1.png
  docs/images/userguide/vtarget_step2.png
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
Labels: documentation

#302 Fix command box output bug for module
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#304 Update DG with module model
  docs/DeveloperGuide.md
  docs/diagrams/ModuleClassDiagram.puml
Labels: documentation

#305 Update Diagram
  docs/images/ModuleClassDiagram.png
Labels: documentation

#306 Fix typos in DG
  docs/DeveloperGuide.md
Labels: bug, documentation

#308 Fix command summary bug in UG for module
  docs/UserGuide.md
Labels: bug, documentation

#309 Fix bug in DG regarding edit module
  docs/DeveloperGuide.md
  docs/diagrams/EditModuleSequenceDiagram.puml
  docs/images/EditModuleSequenceDiagram.png
Labels: bug, documentation

#310 Update User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditStudentActivityDiagram.puml
  docs/diagrams/StudentClassDiagram.puml
  docs/images/EditStudentActivityDiagram.png
  docs/images/StudentClassDiagram.png
Labels: documentation

#311 Add mlist feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/ListModuleSequenceDiagram.puml
  docs/images/ListModuleSequence.png
Labels: documentation

#313 Update PPP
  docs/team/leongdl135.md
Labels: documentation

#314 Add module class implementation for DG
  docs/DeveloperGuide.md
Labels: documentation

#318 Update UG Format
  docs/UserGuide.md
  docs/images/userguide/mlist.png
  docs/images/userguide/mlist_step1.png
  docs/images/userguide/mlist_step2.png
  docs/images/userguide/mview.png
  docs/images/userguide/mview_step1.png
  docs/images/userguide/mview_step2.png
Labels: documentation

#319 Add implementation of vtarget in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewTargetModuleActivityDiagram.puml
  docs/diagrams/ViewTargetModuleSequenceDiagram.puml
  docs/images/ViewTargetModuleActivityDiagram.png
  docs/images/ViewTargetModuleSequenceDiagram.png
  docs/team/bryanngzh.md
  docs/team/lizekai-richard.md
Labels: documentation

#322 Fix typos for UG
  docs/UserGuide.md
Labels: bug, documentation

#325 Update PPP
  docs/team/drkkjh.md
Labels: documentation

#329 Edit addressbookparser to ProfNusParser for DG
  docs/diagrams/EditModuleSequenceDiagram.puml
  docs/diagrams/ViewTargetModuleSequenceDiagram.puml
  docs/images/EditModuleSequenceDiagram.png
  docs/images/ViewTargetModuleSequenceDiagram.png
Labels: documentation

#328 Standardise formatting for UG
  docs/UserGuide.md
Labels: documentation

#330 Add links to PPP for bryanngzh
  docs/team/bryanngzh.md
Labels: documentation

#331 Update puml
  docs/DeveloperGuide.md
  docs/diagrams/EditStuCommandSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/EditStuCommandSequenceDiagram.png
  docs/images/ParserClasses.png
Labels: documentation

#334 Fix typos in UG
  docs/UserGuide.md
Labels: documentation

#338 Fix add student bug
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
Labels: bug

#336 Update About Us page
  docs/AboutUs.md
  docs/team/bryanngzh.md
Labels: documentation

#339 Fix bugs regarding medit requiring modulecode
  src/main/java/seedu/address/logic/commands/module/EditModuleCommand.java
Labels: bug

#337 Change naming in DG for vtarget
  docs/DeveloperGuide.md
Labels: documentation

#342 Fix sview UG
  docs/UserGuide.md
Labels: bug, documentation

#344 Update error message
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/EditTeachingAssistantCommand.java
Labels: documentation

#347 Edit UG
  docs/UserGuide.md
Labels: documentation

#348 Edit UG with pagebreaks
  docs/UserGuide.md
Labels: documentation

#349 Add more pagebreaks
  docs/UserGuide.md
Labels: documentation
